// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psiskpndznunnxxddyzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzaXNrcG5kem51bm54eGRkeXpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMjU4NzcsImV4cCI6MjA3MjgwMTg3N30.xjqXQfSWU6mrRjt4Jz1BCuXamwzWKxAE5NijR7s48s0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});